# Site settings
title: little red computer
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.littleredcomputer.net" # the base hostname & protocol for your site
twitter_username: c0linsmith
github_username:  littleredcomputer

# Build settings

markdown: kramdown

# markdown: redcarpet
# redcarpet:
#   extensions: ['smart', 'fenced_code_blocks']

