# Site settings
title: little red computer
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My uncle has a country place that no one knows about.
  He says it used to be a farm before the Motor Law.
baseurl: "" # the subpath of your site, e.g. /blog/
exclude: ['src']
url: "http://blog.littleredcomputer.net" # the base hostname & protocol for your site
# twitter_username: c0linsmith
github_username:  littleredcomputer

# Build settings

markdown: kramdown

# markdown: redcarpet
# redcarpet:
#   extensions: ['smart', 'fenced_code_blocks']
